// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID                string `json:"id"`
	CarModel          string `json:"car_model"`
	DateOfManufacture string `json:"date_of_manufacture"`
	LastServiceDate   string `json:"last_service_date"`
	LastUsedDate      string `json:"last_used_date"`
	Status            string `json:"status"`
}
